# Welcome to Jekyll!
#
# This config file is built for Minimal Mistakes theme.
# For more info: https://mmistakes.github.io/minimal-mistakes/docs/configuration/

# Site settings
title: Zorba의 개인 블로그
email: zorbalim99@gmail.com
description: >-
  개인 일상과 개발 및 기술 관련 기록을 남기는 블로그입니다.
url: "https://zorba-lim.github.io"
baseurl: ""
repository: "zorba-lim/zorba-lim.github.io"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Author settings
author:
  name: "Zorba Lim"
  avatar: # /assets/images/bio-photo.jpg
  bio: "개인 일상 및 개발 기록 블로그"
  location: "Seoul, Korea"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zorba-lim"

# Themes
remote_theme: "mmistakes/minimal-mistakes"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-include-cache

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      sidebar:
        nav: "main"

# Comments
comments:
  provider: "utterances"
  utterances:
    theme: "github-light"
    issue_term: "pathname"
    label: "comment"
    repository: "zorba-lim/zorba-lim.github.io"

# Social Sharing
share: true

# Navigation
# (Using _data/navigation.yml)

# Others
locale: "ko-KR"
charset: "utf-8"

exclude:
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .github
