# The Site Settings
#
# Specific to Chirpy theme
# https://github.com/cotes2020/jekyll-theme-chirpy

title: Zorba is Free
tagline: 개인 일상과 개발 및 기술 관련 기록을 남기는 블로그입니다.
description: >-
  개인 일상과 개발 및 기술 관련 기록을 남기는 블로그입니다.
url: "https://zorba-lim.github.io"
baseurl: ""
repository: "zorba-lim/zorba-lim.github.io"
author: Zorba Lim

# Timezone and Locale
timezone: Asia/Seoul
lang: ko-KR

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-archives


# Pagination Settings
paginate: 10
paginate_path: "/page:num/"

# Theme settings
theme: jekyll-theme-chirpy
theme_mode: # light, dark
future: true


avatar: /assets/img/avatar.png

social:
  name: Zorba Lim
  email: zorbalim99@gmail.com
  links:
    - https://github.com/zorba-lim

# Google Analytics, Comments, Adsense etc.
# Search Console verification
webmaster_verifications:
  google: "4KZYmtKZD1z3ShpJmxI3_WgD9dwbUrsEULitvWh3xB4"

comments:
  provider: disqus
  disqus:
    shortname: zorba-lim-github-io

# TOC
toc: true
# toc_label: "" # Chirpy에서는 CSS로 처리하는 것이 확실함

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      toc: true
      comments: true



# Collections
collections:
  tabs:
    output: true
    sort_by: order

# Archives
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# Jekyll settings
markdown: kramdown
highlighter: rouge

# Build settings
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .jekyll-cache
  - .jekyll-metadata
  - .github
  - README.md
  - LICENSE
  - task.md
  - implementation_plan.md
  - walkthrough.md
